---
title: "R Notebook"
output: html_notebook
---


```{r}
Sys.setenv(LANG = "en")
Sys.setlocale("LC_TIME", "English")
library(openxlsx)
library(data.table)
library(zoo)
library(lubridate)
library(ggplot2)
library(plotly)
library(stringr)
library(ISOweek)
library(ggthemes)
```
OLD DATA SOURCE : https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide
```{r}
# DT_old <- fread("data_old.csv")
# 
# 
# DT_old[,date:=as.Date(dateRep, "%d/%m/%Y")]
# 
# 
# countries <- c("Austria", "Belgium", "France", "Luxembourg", "Netherlands", "Germany", "Slovenia", "Switzerland")
# dt_from <- as.Date("2020-02-01")
# dt_to <- as.Date("2020-11-28")
# 
# DT_old <- DT_old[countriesAndTerritories %in% countries & date >= dt_from & date <= dt_to][order(date)]
# DT_old <-  DT_old[,c("countriesAndTerritories","date", "cases", "deaths")]
# 
# DT_old.cases <- DT_old[, "ravg_" := lapply(.SD, rollmean, k = 14, na.pad = TRUE),
#   by = countriesAndTerritories, .SDcols = c("cases")
# ]
# 
# DT_old.death <-  DT_old[, "ravg_" := lapply(.SD, rollmean, k = 14, na.pad = TRUE),
#   by = countriesAndTerritories, .SDcols = c("deaths")
# ]
```



DATA SOURCE : https://www.ecdc.europa.eu/en/publications-data/data-national-14-day-notification-rate-covid-19
```{r}


DT <- fread("data.csv")

DT[, year_week:=str_replace(year_week, "-", "-W")]
DT[, year_week:=paste0(year_week, "-1")]
DT[, date:=ISOweek2date(year_week)]

countries <- c("Austria", "Belgium", "France", "Luxembourg", "Netherlands", "Germany", "Slovenia", "Switzerland")
dt_from <- as.Date("2020-02-01")
dt_to <- as.Date("2020-11-28")

DT.cases <- DT[country %in% countries & date >= dt_from & date <= dt_to & indicator == "cases"][order(date)]
DT.death <- DT[country %in% countries & date >= dt_from & date <= dt_to & indicator == "deaths"][order(date)]

DT.cases[, "ravg_" := lapply(.SD, rollmean, k = 2, na.pad = TRUE),
  by = country, .SDcols = c("rate_14_day")
]

DT.death[, "ravg_" := lapply(.SD, rollmean, k = 2, na.pad = TRUE),
  by = country, .SDcols = c("rate_14_day")
]
```

```{r}
options(scipen=10000)
g <- ggplot(DT.cases, aes(date, rate_14_day, color = country)) +
  geom_line(size = .8) +
  scale_color_brewer(palette = "Set1") +
  theme_fivethirtyeight() +
  theme(legend.title = element_blank()) +
  # labs(
  #   title = "14 days notification rate of newly reported COVID19 Cases ",
  #   subtitle = "per 100 000 population",
  #   caption = "Data source:                       "
  # ) +
  theme(plot.title = element_text(size = 14))
g
ggsave("Covid19_Cases.png", scale = 2, dpi = 300, width = 20, height = 12, units = "cm")

```
```{r}
options(scipen=10000)
g <- ggplot(DT.death, aes(date, rate_14_day, color = country)) +
  geom_line(size = .8) +
  scale_color_brewer(palette = "Set1") +
  theme_fivethirtyeight() +
  theme(legend.title = element_blank()) +
  # labs(
  #   title = "14 days notification rate of newly reported COVID19 Deaths",
  #   subtitle = "per 100 000 population", caption = "Data source:                       "
  # ) +
  theme(plot.title = element_text(size = 14))
g
ggsave("Covid19_Deaths.png", scale = 2, dpi = 300, width = 20, height = 12, units = "cm")
```
