---
title: "R Notebook"
output: html_notebook
---



```{r}
Sys.setenv(LANG = "en")
Sys.setlocale("LC_TIME", "English")
library(openxlsx)
library(data.table)
library(ggplot2)
library(ggthemes)
library(bbplot)


```


```{r}

plotChart <- function(sheetIndex) {
  DT_raw <- openxlsx::readWorkbook("data/input/Dental_HIT.xlsx", sheet = sheetIndex, colNames = F)
  plotTitle <- DT_raw$X1[[1]]
  DT <- openxlsx::readWorkbook("data/input/Dental_HIT.xlsx", sheet = sheetIndex, rows = seq(2, 30, 1))
  setDT(DT)
  DT[is.na(DT)] <- 0
  if ("X14" %in% names(DT)) {
    DT[, `X14` := NULL]
  }
  if ("2019" %in% names(DT)) {
    DT[, `2019` := NULL]
  }

  DT.m1 <- melt(DT,
    measure.vars = c(
      "2008", "2009", "2010", "2011", "2012", "2013",
      "2014", "2015", "2016", "2017", "2018"
    ),
    variable.name = "year", value.name = "value", variable.factor = F
  )
  DT.m1[, Country := as.factor(Country)]




  cols <- c("2008" = "#d36651", "2018" = "#5e2215")
  p <- ggplot(DT[Country != "Switzerland"], aes(Country, `2008`)) +
    geom_segment(aes(x = reorder(Country, `2018`), xend = reorder(Country, `2018`), y = `2008`, yend = `2018`), color = "#de6f70") +
    geom_point(data = DT.m1[year %in% c("2008", "2018") & Country != "Switzerland"], aes(x = Country, y = value, color = year)) +
    # geom_point(aes(x=Country,y = `2018`), color = "deeppink", shape = 21, fill = "white", stroke = 1, size = 3, text = "2018") +
    # theme_fivethirtyeight() +
    labs(title = plotTitle, subtitle = "", caption = "") +
    coord_flip() +
    scale_color_manual(values = cols) +
    theme_fivethirtyeight() +
    ylab("%") +
    theme(axis.text.y = element_text(size = 8)) +
    theme(legend.title = element_blank())

  ggsave(paste0("data/", sheetIndex, ".png"))
}
```

```{r}
sheets <- getSheetNames("data/input/Dental_HIT.xlsx")

lapply(sheets, plotChart)
```
