---
title: "IHME Plots"
output: html_notebook
---

# source : http://ghdx.healthdata.org/gbd-results-tool

```{r}
library(data.table)
library(ggplot2)
library(bbplot)
library(openxlsx)
```


```{r}
DT <- fread("./data/IHME-GBD_2019_DATA-992318fc-1.csv")
openxlsx::write.xlsx(DT,".data/IHME-GBD_2019_DATA-992318fc-1.xlsx")

DT[, sum_val := sum(val), by = .(location_name, year)]
DT[, location_name := as.factor(location_name)]
```

```{r}
ggplot(DT[year == 2019], aes(reorder(location_name, sum_val), val, fill = as.factor(cause_name))) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme(legend.title = element_blank()) +
  bbc_style() +
  scale_fill_brewer(palette = "Spectral") +
  t+guides(fill=guide_legend(nrow = 2))+ theme(legend.position='bottom', 
        legend.justification='left',
        legend.direction='horizontal')
# theme(axis.text.x = element_text(angle = 45,  hjust=1))
```
```{r}
font <- "Helvetica"
t <- theme(
  plot.title = ggplot2::element_text(
    family = font,
    size = 28, face = "bold", color = "#222222"
  ), plot.subtitle = ggplot2::element_text(
    family = font,
    size = 22, margin = ggplot2::margin(9, 0, 9, 0)
  ), plot.caption = ggplot2::element_blank(),
  legend.position = "top", legend.text.align = 0, legend.background = ggplot2::element_blank(),
  legend.title = ggplot2::element_blank(), legend.key = ggplot2::element_blank(),
  legend.text = ggplot2::element_text(
    family = font, size = 10,
    color = "#222222"
  ), axis.title = ggplot2::element_blank(),
  axis.text = ggplot2::element_text(
    family = font, size = 8,
    color = "#222222"
  ), axis.text.x = ggplot2::element_text(margin = ggplot2::margin(5,
    b = 10
  )), axis.ticks = ggplot2::element_blank(),
  axis.line = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
  panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
  panel.grid.major.x = ggplot2::element_blank(), panel.background = ggplot2::element_blank(),
  strip.background = ggplot2::element_rect(fill = "white"),
  strip.text = ggplot2::element_text(size = 22, hjust = 0)
)
```
